import Head from 'next/head'
import Image from 'next/image'
import NonAuth from '../Containers/nonauth'
import {useStore} from '../context/Auth';
import React, { useEffect } from 'react';
import Navbar from '../Components/Navbar/Navbar';
import Createpost from '../Components/Createpost/Createpost';
import { GetServerSideProps, GetStaticProps } from 'next';
import axios from 'axios';
import Feed from '../Components/Feed/Feed';


const Home = ({data}:any) =>{

const {user, getprofile,profile} = useStore();

  
  useEffect(() => {
   getprofile();
  }, [])


console.log(profile)


  return (
    <div>
      <Head>
        <title>Flake World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {   user===null?<NonAuth/>:(
    <>
      <Navbar title={"Home"}/>
      <Createpost/>
      <div style={{backgroundColor:"rgb(239, 243, 244)",height:"15px"}}></div>
      <Feed data={data}/>
     </>
      )
    
    }
     
     
     
     </div>
      
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await axios.get(`${process.env.NEXT_URL}/api/getposts`);



  
  return {
      props: {
        data:res.data
      }
  };
}






export default Home;
